name: Bandit Security Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer l'environnement Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Étape 3 : Installer Bandit
      - name: Install Bandit
        run: pip install bandit

      # Étape 4 : Exécuter Bandit
      - name: Run Bandit Security Scan
        run: bandit -r app/ -f json -o bandit-report.json

      # Étape 5 : Télécharger le rapport de Bandit
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.json
