name: SCA Analysis
on:
  push:
    branches:
      - main
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit security scan
        run: bandit -r .
